<a href="https://colab.research.google.com/github/srilatha124/git-project/blob/main/salary_prediction_SLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
data=pd.read_csv('Salary_Data_SLR.csv')

In [70]:
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [71]:
X=data.iloc[:,0].values
X=X.reshape(-1,1)

In [72]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [73]:
Y=data.iloc[:,1].values

In [74]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [76]:
X_train

array([[ 2.2],
       [ 4. ],
       [ 4.1],
       [ 1.3],
       [ 8.2],
       [10.5],
       [ 3.2],
       [ 5.3],
       [ 4.5],
       [ 7.1],
       [ 6. ],
       [ 9.6],
       [ 4. ],
       [ 2. ],
       [ 3. ],
       [ 5.1],
       [ 3.2],
       [ 1.5],
       [ 4.9],
       [ 2.9],
       [ 9.5],
       [ 1.1],
       [ 3.7],
       [ 8.7]])

In [77]:
X_test

array([[ 9. ],
       [ 6.8],
       [ 5.9],
       [ 3.9],
       [10.3],
       [ 7.9]])

In [78]:
Y_train

array([ 39891.,  56957.,  57081.,  46205., 113812., 121872.,  64445.,
        83088.,  61111.,  98273.,  93940., 112635.,  55794.,  43525.,
        60150.,  66029.,  54445.,  37731.,  67938.,  56642., 116969.,
        39343.,  57189., 109431.])

In [79]:
Y_test

array([105582.,  91738.,  81363.,  63218., 122391., 101302.])

In [83]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [84]:
regressor.coef_

array([9566.75084301])

In [85]:
regressor.intercept_

25357.483439490446

In [86]:
regressor.predict([[6]])

array([82757.98849756])

In [88]:
regressor.predict(X_test)

array([111458.2410266 ,  90411.38917197,  81801.31341326,  62667.81172724,
       123895.01712252, 100934.81509929])

In [89]:
Y_test

array([105582.,  91738.,  81363.,  63218., 122391., 101302.])